// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Test.Api.Data;
using Test.Api.Migrations.EfModel;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TodosContext), typeof(TodosContextModel))]
