// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Test.Api.Data;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Test.Api.Migrations.EfModel
{
    public static class TodoEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref long Id(TodoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(TodoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DueBy>k__BackingField")]
        public static extern ref DateOnly? DueBy(TodoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsComplete>k__BackingField")]
        public static extern ref bool IsComplete(TodoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Title>k__BackingField")]
        public static extern ref string Title(TodoEntity @this);
    }
}
